server:
  port: 9013
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_example?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
